/* Holodori Roster Recognizer v1.0 browser worker.
   Pure browser implementation: Canvas + typed arrays; no OpenCV/Tesseract/runtime network dependency. */
'use strict';

const VERSION='1.0.2';
const API_VERSION=1;
const BASE={cardW:286,cardH:416,pitch:309,rowPitch:432,iconLeft:57,iconTop:42};
const ATTR_HUES={
  'CardAttributeType_CARD_ATTRIBUTE_TYPE_ATTRIBUTE_1':172,
  'CardAttributeType_CARD_ATTRIBUTE_TYPE_ATTRIBUTE_2':66,
  'CardAttributeType_CARD_ATTRIBUTE_TYPE_ATTRIBUTE_3':19,
};
const GROUP_HSV={gamers:[104,187,255],gen1:[159,165,255],gen4:[20,173,255],gen3:[49,142,211],gen5:[169,111,255],holox:[141,168,208],myth:[22,132,205],promise:[33,162,218],advent:[116,118,168],gen0:[110.5,114.5,255],gen2:[112,175,255],id2:[82,173,227],id3:[91,144.5,233],regloss:[1,200,210]};
const GROUP_TO_METADATA={gen0:'grp-gen_0',gen1:'grp-gen_1',gen2:'grp-gen_2',gen3:'grp-gen_3',gen4:'grp-gen_4',gen5:'grp-gen_5',gamers:'grp-gamers',holox:'grp-holox',myth:'grp-myth',promise:'grp-promise',advent:'grp-advent',id1:'grp-indonesia-gen_1',id2:'grp-indonesia-gen_2',id3:'grp-indonesia-gen_3',regloss:'grp-regloss'};
let REGISTRY=[],BY_ID=new Map(),REFS=new Map(),REF_META=null,DIGITS=null,REGISTRY_HASH='';
let ready=false;

function clamp(x,a,b){return x<a?a:x>b?b:x;}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length&1?b[m]:(b[m-1]+b[m])/2;}
function hueDist(a,b){const d=Math.abs(a-b);return Math.min(d,180-d);}
function rgbHsv(r,g,b){
  const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;
  if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=30;if(h<0)h+=180;}
  const s=mx?255*d/mx:0;return [h,s,mx];
}
function b64bytes(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a;}
function canvas(w,h){return new OffscreenCanvas(Math.max(1,Math.round(w)),Math.max(1,Math.round(h)));}
function getData(c){return c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height);}

function normalizeChannel(a){let sum=0,sum2=0;for(let i=0;i<a.length;i++){sum+=a[i];sum2+=a[i]*a[i];}const mean=sum/a.length,sd=Math.sqrt(Math.max(1e-8,sum2/a.length-mean*mean));for(let i=0;i<a.length;i++)a[i]=(a[i]-mean)/sd;return a;}
function denseDescriptorFromRGB(rgb,w,h){
  const n=w*h,y=new Float32Array(n),c1=new Float32Array(n),c2=new Float32Array(n);
  for(let i=0,j=0;i<n;i++,j+=3){const r=rgb[j]/255,g=rgb[j+1]/255,b=rgb[j+2]/255;y[i]=.299*r+.587*g+.114*b;c1[i]=r-g;c2[i]=b-g;}
  normalizeChannel(y);normalizeChannel(c1);normalizeChannel(c2);
  const mag=new Float32Array(n);
  for(let yy=1;yy<h-1;yy++)for(let xx=1;xx<w-1;xx++){
    const i=yy*w+xx;
    const gx=(-y[i-w-1]+y[i-w+1]-2*y[i-1]+2*y[i+1]-y[i+w-1]+y[i+w+1]);
    const gy=(-y[i-w-1]-2*y[i-w]-y[i-w+1]+y[i+w-1]+2*y[i+w]+y[i+w+1]);
    mag[i]=Math.hypot(gx,gy);
  }
  normalizeChannel(mag);return [y,c1,c2,mag];
}
function denseDescriptorFromCanvas(c,w=48,h=52){
  const t=canvas(w,h),ctx=t.getContext('2d',{willReadFrequently:true});ctx.drawImage(c,72,72,153,183,0,0,w,h);const d=ctx.getImageData(0,0,w,h).data,rgb=new Uint8Array(w*h*3);for(let i=0,j=0;i<d.length;i+=4){rgb[j++]=d[i];rgb[j++]=d[i+1];rgb[j++]=d[i+2];}return denseDescriptorFromRGB(rgb,w,h);
}
function channelCorr(a,b,w,h,dx,dy){
  const ax0=Math.max(0,-dx),bx0=Math.max(0,dx),ay0=Math.max(0,-dy),by0=Math.max(0,dy),ww=w-Math.abs(dx),hh=h-Math.abs(dy);if(ww<8||hh<8)return -1;
  let sa=0,sb=0,saa=0,sbb=0,sab=0,n=0;
  for(let y=0;y<hh;y++){let ai=(ay0+y)*w+ax0,bi=(by0+y)*w+bx0;for(let x=0;x<ww;x++,ai++,bi++){const av=a[ai],bv=b[bi];sa+=av;sb+=bv;saa+=av*av;sbb+=bv*bv;sab+=av*bv;n++;}}
  const cov=sab-sa*sb/n,va=saa-sa*sa/n,vb=sbb-sb*sb/n;return cov/Math.sqrt(Math.max(1e-10,va*vb));
}
function denseScore(q,r,w=48,h=52){let best=-9;for(let dy=-4;dy<=4;dy+=2)for(let dx=-4;dx<=4;dx+=2){const s=.40*channelCorr(q[0],r[0],w,h,dx,dy)+.15*channelCorr(q[1],r[1],w,h,dx,dy)+.15*channelCorr(q[2],r[2],w,h,dx,dy)+.30*channelCorr(q[3],r[3],w,h,dx,dy);if(s>best)best=s;}return best;}

function morphClose(mask,w,h){
  const d=new Uint8Array(mask.length),e=new Uint8Array(mask.length);
  for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let on=0;for(let yy=-1;yy<=1&&!on;yy++)for(let xx=-1;xx<=1;xx++)if(mask[(y+yy)*w+x+xx]){on=1;break;}d[y*w+x]=on;}
  for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let on=1;for(let yy=-1;yy<=1&&on;yy++)for(let xx=-1;xx<=1;xx++)if(!d[(y+yy)*w+x+xx]){on=0;break;}e[y*w+x]=on;}
  return e;
}
function connectedComponents(mask,w,h){
  const seen=new Uint8Array(mask.length),queue=new Int32Array(mask.length),out=[];
  for(let idx=0;idx<mask.length;idx++)if(mask[idx]&&!seen[idx]){let qh=0,qt=0;queue[qt++]=idx;seen[idx]=1;let area=0,minx=w,miny=h,maxx=0,maxy=0,sx=0,sy=0;
    while(qh<qt){const p=queue[qh++],y=(p/w)|0,x=p-y*w;area++;sx+=x;sy+=y;if(x<minx)minx=x;if(x>maxx)maxx=x;if(y<miny)miny=y;if(y>maxy)maxy=y;
      for(let yy=Math.max(0,y-1);yy<=Math.min(h-1,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(w-1,x+1);xx++){const n=yy*w+xx;if(mask[n]&&!seen[n]){seen[n]=1;queue[qt++]=n;}}
    }out.push({area,minx,miny,maxx,maxy,cx:sx/area,cy:sy/area});
  }return out;
}
function clusterValues(items,key,tol){const groups=[];for(const it of [...items].sort((a,b)=>a[key]-b[key])){let found=null;for(const g of groups){if(Math.abs(it[key]-median(g.map(x=>x[key])))<=tol){found=g;break;}}(found||groups[groups.push([])-1]).push(it);}return groups;}
function estimateXLatticeDesktop(circles,yGroups,imageW){
  const plausible=[];for(const g of yGroups){const xs=g.map(c=>c.x).sort((a,b)=>a-b);for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++){const d=xs[j]-xs[i];if(d>=BASE.pitch*.75&&d<=BASE.pitch*1.25)plausible.push(d);}}
  let pitch=BASE.pitch;if(plausible.length){const bins=new Map();for(const d of plausible){const k=Math.round(d/4)*4;if(!bins.has(k))bins.set(k,[]);bins.get(k).push(d);}let best=[];for(const a of bins.values())if(a.length>best.length)best=a;pitch=median(best);}
  const tol=Math.max(14,.055*pitch),xsAll=circles.map(c=>c.x);let anchor=xsAll[0],bestScore=-1;for(const a of xsAll){let score=0;for(const x of xsAll)if(Math.abs((x-a)-Math.round((x-a)/pitch)*pitch)<=tol)score++;if(score>bestScore){bestScore=score;anchor=a;}}
  const aligned=[];for(const x of xsAll){const k=Math.round((x-anchor)/pitch);if(Math.abs(x-(anchor+k*pitch))<=tol)aligned.push([x,k]);}const phase=median(aligned.map(([x,k])=>x-k*pitch)),ks=aligned.map(([x])=>Math.round((x-phase)/pitch));
  let best=null,kmin=Math.min(...ks),kmax=Math.max(...ks);for(let k0=kmin-2;k0<=kmax+1;k0++){const centers=Array.from({length:6},(_,i)=>phase+(k0+i)*pitch);let support=0;for(const k of ks)if(k>=k0&&k<=k0+5)support++;let visible=0;for(const xc of centers){const l=xc-BASE.iconLeft*(pitch/BASE.pitch),r=l+BASE.cardW*(pitch/BASE.pitch);visible+=Math.max(0,Math.min(imageW,r)-Math.max(0,l))/(BASE.cardW*(pitch/BASE.pitch));}const cm=centers.reduce((s,xc)=>s+xc-BASE.iconLeft*(pitch/BASE.pitch)+BASE.cardW*(pitch/BASE.pitch)/2,0)/6,cp=Math.abs(cm-imageW/2)/pitch,score=support*10+visible-cp*.15;if(!best||score>best.score)best={score,centers};}
  return [best.centers,pitch];
}
function estimateXLatticeAdaptive(circles,yGroups,imageW){
  // Infer the fundamental six-column pitch from repeated same-row icon spacing.
  // Mobile embeds the roster in only part of the screenshot, so full viewport width
  // must never be used as a proxy for card scale.
  const bins=new Map();
  for(const g of yGroups){const xs=g.map(c=>c.x).sort((a,b)=>a-b);for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++){const d=xs[j]-xs[i];if(d>=70&&d<=380){const k=Math.round(d/4)*4;if(!bins.has(k))bins.set(k,[]);bins.get(k).push(d);}}}
  let pitch=BASE.pitch;
  if(bins.size){let maxn=0;for(const v of bins.values())maxn=Math.max(maxn,v.length);const strong=[...bins.entries()].filter(([,v])=>v.length>=Math.max(3,Math.ceil(maxn*.55))).sort((a,b)=>a[0]-b[0]);if(strong.length)pitch=median(strong[0][1]);else{let best=[];for(const v of bins.values())if(v.length>best.length)best=v;pitch=median(best);}}
  const tol=Math.max(8,.06*pitch),expectedR=36*pitch/BASE.pitch,fit=circles.filter(c=>!c.r||c.r>=expectedR*.65&&c.r<=expectedR*1.5);const use=fit.length>=3?fit:circles,xsAll=use.map(c=>c.x);
  let anchor=xsAll[0],bestScore=-1;for(const a of xsAll){let score=0;for(const x of xsAll)if(Math.abs((x-a)-Math.round((x-a)/pitch)*pitch)<=tol)score++;if(score>bestScore){bestScore=score;anchor=a;}}
  const aligned=[];for(const c of use){const k=Math.round((c.x-anchor)/pitch);if(Math.abs(c.x-(anchor+k*pitch))<=tol)aligned.push([c,k]);}
  const phase=median(aligned.map(([c,k])=>c.x-k*pitch)),tagged=aligned.map(([c])=>({k:Math.round((c.x-phase)/pitch),y:c.y}));const ks=tagged.map(t=>t.k);
  const groups=[];for(const t of [...tagged].sort((a,b)=>a.y-b.y)){let hit=null;for(const g of groups){if(Math.abs(t.y-median(g.map(q=>q.y)))<=8){hit=g;break;}}if(hit)hit.push(t);else groups.push([t]);}
  let best=null,kmin=Math.min(...ks),kmax=Math.max(...ks);for(let k0=kmin-1;k0<=kmax;k0++){let score=0,total=0;for(const g of groups){const n=new Set(g.filter(t=>t.k>=k0&&t.k<=k0+5).map(t=>t.k)).size;if(n>=2)score+=n*n;total+=n;}score+=.1*total;if(!best||score>best.score)best={score,k0};}
  return [Array.from({length:6},(_,i)=>phase+(best.k0+i)*pitch),pitch];
}
function estimateXLattice(circles,yGroups,imageW){const a=estimateXLatticeAdaptive(circles,yGroups,imageW);return a[1]>=230?estimateXLatticeDesktop(circles,yGroups,imageW):a;}
function attrMaskFromImageData(img){const {data,width:w,height:h}=img,m=new Uint8Array(w*h);for(let i=0,p=0;i<data.length;i+=4,p++){const [hh,s,v]=rgbHsv(data[i],data[i+1],data[i+2]);if(s>100&&v>90&&(hueDist(hh,172)<18||hueDist(hh,66)<18||hueDist(hh,19)<18))m[p]=1;}return m;}
function integral(mask,w,h){const ii=new Int32Array((w+1)*(h+1));for(let y=0;y<h;y++){let row=0;for(let x=0;x<w;x++){row+=mask[y*w+x];ii[(y+1)*(w+1)+x+1]=ii[y*(w+1)+x+1]+row;}}return ii;}
function rectSum(ii,w,h,x0,y0,x1,y1){x0=clamp(Math.round(x0),0,w);x1=clamp(Math.round(x1),0,w);y0=clamp(Math.round(y0),0,h);y1=clamp(Math.round(y1),0,h);const s=w+1;return ii[y1*s+x1]-ii[y0*s+x1]-ii[y1*s+x0]+ii[y0*s+x0];}
function fitGeometry(bitmap){
  const factor=1900/bitmap.width,canonH=Math.max(1,Math.round(bitmap.height*factor));const halfW=950,halfH=Math.max(1,Math.round(canonH/2)),c=canvas(halfW,halfH),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,halfW,halfH);const img=ctx.getImageData(0,0,halfW,halfH);let mask=morphClose(attrMaskFromImageData(img),halfW,halfH);const comps=connectedComponents(mask,halfW,halfH),circles=[];
  for(const z of comps){const bw=z.maxx-z.minx+1,bh=z.maxy-z.miny+1;if(bw>=21&&bw<=46&&bh>=21&&bh<=46&&bw/bh>=.6&&bw/bh<=1.6&&z.area>=190)circles.push({x:z.cx*2,y:z.cy*2,area:z.area,r:Math.sqrt(z.area/Math.PI)*2});}
  if(!circles.length)throw new Error('Could not find roster attribute icons.');const yg=clusterValues(circles,'y',8),mobileLayout=(bitmap.width/bitmap.height)>1.9,[xs,pitch]=(mobileLayout?estimateXLatticeAdaptive(circles,yg,1900):estimateXLatticeDesktop(circles,yg,1900)),rp=pitch*(432/309),tolx=Math.max(14,.055*pitch),mapped=[];
  for(const g of yg){const cols=new Map();for(const z of g){let col=0,bd=Infinity;for(let i=0;i<xs.length;i++){const d=Math.abs(z.x-xs[i]);if(d<bd){bd=d;col=i;}}if(bd<=tolx)cols.set(col,z);}if(cols.size)mapped.push({y:median([...cols.values()].map(z=>z.y)),cols});}
  if(!mapped.length)throw new Error('Could not fit roster grid.');const strong=mapped.filter(x=>x.cols.size>=4),base=(strong.length?strong:mapped).sort((a,b)=>b.cols.size-a.cols.size)[0].y,rowMap=new Map();for(const m of mapped){const k=Math.round((m.y-base)/rp),ly=base+k*rp;if(Math.abs(m.y-ly)>Math.max(10,.03*rp))continue;if(!rowMap.has(k))rowMap.set(k,{ys:[],cols:new Map()});const r=rowMap.get(k);r.ys.push(m.y);for(const [cc,z] of m.cols)r.cols.set(cc,z);}
  const anchors=[];for(const r of rowMap.values()){const y=Math.round(median(r.ys));for(const col of r.cols.keys())anchors.push([y,col]);}
  const ys=[...new Set(anchors.map(x=>x[0]))].sort((a,b)=>a-b),b0=ys[0],phase=median(ys.map(y=>y-Math.round((y-b0)/rp)*rp)),ii=integral(mask,halfW,halfH);
  function iconScore(x,y){const xx=x/2,yy=y/2,rr=12.5,x0=xx-rr,x1=xx+rr+1,y0=yy-rr,y1=yy+rr+1,area=Math.max(1,(clamp(x1,0,halfW)-clamp(x0,0,halfW))*(clamp(y1,0,halfH)-clamp(y0,0,halfH)));return rectSum(ii,halfW,halfH,x0,y0,x1,y1)/area;}
  return {factor,canonH,xs,pitch,rowPitch:rp,phase,observedYs:ys,mobileLayout,iconScore,componentCount:circles.length};
}
function extractCard(bitmap,geom,rowY,col){const s=geom.pitch/BASE.pitch,left=geom.xs[col]-BASE.iconLeft*s,top=rowY-BASE.iconTop*s,w=BASE.cardW*s,h=BASE.cardH*s;const src={x:left/geom.factor,y:top/geom.factor,w:w/geom.factor,h:h/geom.factor};const c=canvas(BASE.cardW,BASE.cardH),ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#000';ctx.fillRect(0,0,BASE.cardW,BASE.cardH);const sx=Math.max(0,src.x),sy=Math.max(0,src.y),ex=Math.min(bitmap.width,src.x+src.w),ey=Math.min(bitmap.height,src.y+src.h);if(ex>sx&&ey>sy){const dx=(sx-src.x)/src.w*BASE.cardW,dy=(sy-src.y)/src.h*BASE.cardH,dw=(ex-sx)/src.w*BASE.cardW,dh=(ey-sy)/src.h*BASE.cardH;ctx.drawImage(bitmap,sx,sy,ex-sx,ey-sy,dx,dy,dw,dh);}return {canvas:c,box:[Math.round(src.x),Math.round(src.y),Math.round(src.w),Math.round(src.h)],visibleHeight:Math.max(0,ey-sy),missingTop:Math.max(0,-src.y)/src.h};}
function pixelsROI(c,x0,y0,x1,y1){const ctx=c.getContext('2d',{willReadFrequently:true}),xx0=clamp(Math.round(x0),0,c.width),yy0=clamp(Math.round(y0),0,c.height),xx1=clamp(Math.round(x1),0,c.width),yy1=clamp(Math.round(y1),0,c.height);if(xx1<=xx0||yy1<=yy0)return null;return ctx.getImageData(xx0,yy0,xx1-xx0,yy1-yy0);}
function classifyRarity(c){const im=pixelsROI(c,80,390,225,414);if(!im)return [null,0];const d=im.data;let valid=0,yellow=0,cyan=0,mag=0,sat=0,sum=0,sum2=0,nv=0;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],[h,s,v]=rgbHsv(r,g,b);sum+=r+g+b;sum2+=r*r+g*g+b*b;nv+=3;if(v<=40)continue;valid++;if(h>=17&&h<=38&&s>=70&&v>=130)yellow++;if(h>=80&&h<=115&&s>=55&&v>=100)cyan++;if((h>=130||h<=10)&&s>=55&&v>=100)mag++;if(s>=70)sat++;}const px=d.length/4;if(valid<.55*px)return [null,0];yellow/=valid;cyan/=valid;mag/=valid;sat/=valid;const rainbow=cyan+mag;if(yellow>=.20)return [4,clamp(.90+.12*Math.min(1,(yellow-.20)/.45),.90,.995)];if(rainbow>=.18&&sat>=.35)return [5,clamp(.90+.10*Math.min(1,(rainbow-.18)/.35),.90,.995)];const mean=sum/nv,std=Math.sqrt(Math.max(0,sum2/nv-mean*mean));if(sat<=.22&&yellow<.08&&rainbow<.12&&std>=18)return [3,clamp(.94+.05*Math.min(1,(std-18)/18),.94,.995)];return [null,0];}
function classifyAttribute(c){const im=pixelsROI(c,29,14,85,70);if(!im)return [null,0];const hues=[];for(let i=0;i<im.data.length;i+=4){const [h,s,v]=rgbHsv(im.data[i],im.data[i+1],im.data[i+2]);if(s>120&&v>100)hues.push(h);}if(hues.length<80)return [null,0];const h=median(hues),rank=Object.entries(ATTR_HUES).map(([id,x])=>[hueDist(h,x),id]).sort((a,b)=>a[0]-b[0]),bd=rank[0][0],sd=rank[1][0],conf=.75*Math.max(0,1-bd/25)+.25*clamp((sd-bd)/25,0,1);return [rank[0][1],conf,h];}
function groupDistance(a,b){const dh=hueDist(a[0],b[0])/18,ds=Math.abs(a[1]-b[1])/70,dv=Math.abs(a[2]-b[2])/80;return Math.sqrt(2.2*dh*dh+.8*ds*ds+.7*dv*dv);}
function classifyGroup(c){const im=pixelsROI(c,155,5,282,55);if(!im)return [null,0];const hs=[],ss=[],vs=[];for(let i=0;i<im.data.length;i+=4){const q=rgbHsv(im.data[i],im.data[i+1],im.data[i+2]);if(q[1]>60&&q[2]>80){hs.push(q[0]);ss.push(q[1]);vs.push(q[2]);}}if(hs.length<100)return [null,0];const sample=[median(hs),median(ss),median(vs)],r=Object.entries(GROUP_HSV).map(([k,v])=>[groupDistance(sample,v),k]).sort((a,b)=>a[0]-b[0]),bd=r[0][0],sd=r[1][0],cc=.75*Math.exp(-1.5*bd)+.25*clamp((sd-bd)/.65,0,1);return [r[0][1],cc,sample];}
function buildCandidates(attr,group,rarity){let a=REGISTRY;if(rarity!=null)a=a.filter(c=>c.rarity===rarity);if(attr)a=a.filter(c=>c.attributeId===attr);if(group)a=a.filter(c=>!c.groupIds?.length||c.groupIds.includes(group));if(group){const known=new Set(Object.values(GROUP_TO_METADATA)),extra=REGISTRY.filter(c=>(rarity==null||c.rarity===rarity)&&(!attr||c.attributeId===attr)&&(!c.groupIds?.length||!c.groupIds.some(g=>known.has(g))));const seen=new Set(a.map(c=>c.id));a=a.concat(extra.filter(c=>!seen.has(c.id)));}return a;}
function recognizeIdentity(card,rarity,missingTop){const [ar,ac]=classifyAttribute(card),[gk,gc]=classifyGroup(card),gidRaw=GROUP_TO_METADATA[gk]||null,attr=ac>=.72?ar:null,gid=gc>=.90?gidRaw:null,cand=buildCandidates(attr,gid,rarity);const base={attributeId:ar,attributeFilterId:attr,attributeConfidence:ac,groupKey:gk,groupId:gidRaw,groupFilterId:gid,groupConfidence:gc,rarity,candidateIds:cand.map(c=>c.id),indexFresh:REF_META?.count===REGISTRY.length&&REF_META?.registrySourceHash===REGISTRY_HASH};if(!cand.length)return {...base,cardId:null,confidence:0,source:'unresolved',alternatives:[]};if(cand.length===1){const c=cand[0];return {...base,cardId:c.id,member:c.member,cardName:c.name,confidence:Math.min(.995,.90+.05*Math.min(ac,gc||1)),source:'metadata-unique',alternatives:[]};}if(!base.indexFresh)return {...base,cardId:null,confidence:0,source:'needs-reference-refresh',alternatives:[]};if(missingTop>.25&&!attr&&!gid)return {...base,cardId:null,confidence:0,source:'needs-review-clipped',alternatives:[]};const q=denseDescriptorFromCanvas(card),scores=[];for(const c of cand){const r=REFS.get(c.id);if(r)scores.push([denseScore(q,r),c]);}scores.sort((a,b)=>b[0]-a[0]);if(!scores.length)return {...base,cardId:null,confidence:0,source:'reference-missing',alternatives:[]};const top=scores[0][0],margin=top-(scores[1]?.[0]??-1);if(top>=.28&&margin>=.015){const c=scores[0][1],conf=Math.min(.995,.62+.30*Math.min(1,Math.max(0,(top-.28)/.35))+.10*Math.min(1,margin/.25));return {...base,cardId:c.id,member:c.member,cardName:c.name,confidence:conf,source:'dense-reference',alternatives:scores.slice(0,5).map(([score,x])=>({card_id:x.id,score}))};}return {...base,cardId:null,confidence:0,source:'needs-review',alternatives:scores.slice(0,5).map(([score,x])=>({card_id:x.id,score}))};}

function binaryCC(mask,w,h){return connectedComponents(mask,w,h);}
function normalizeGlyph(mask,w,h,W=28,H=40){let minx=w,miny=h,maxx=-1,maxy=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(mask[y*w+x]){if(x<minx)minx=x;if(x>maxx)maxx=x;if(y<miny)miny=y;if(y>maxy)maxy=y;}const out=new Float32Array(W*H);if(maxx<minx)return out;const cw=maxx-minx+1,ch=maxy-miny+1,s=Math.min((W-4)/cw,(H-4)/ch),nw=Math.max(1,Math.round(cw*s)),nh=Math.max(1,Math.round(ch*s)),ox=((W-nw)/2)|0,oy=((H-nh)/2)|0;for(let yy=0;yy<nh;yy++)for(let xx=0;xx<nw;xx++){const sx=minx+clamp(Math.round((xx+.5)/nw*cw-.5),0,cw-1),sy=miny+clamp(Math.round((yy+.5)/nh*ch-.5),0,ch-1);out[(oy+yy)*W+ox+xx]=mask[sy*w+sx]?1:0;}return out;}
function cosine(a,b){let ab=0,aa=0,bb=0;for(let i=0;i<a.length;i++){ab+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return ab/Math.sqrt(Math.max(1e-10,aa*bb));}
function classifyDigit(glyph,kind){const by=[];for(const [d,protos] of Object.entries(DIGITS[kind]||{})){let best=-1;for(const p of protos){const s=cosine(glyph,p);if(s>best)best=s;}by.push([best,d]);}by.sort((a,b)=>b[0]-a[0]);return {digit:by[0]?.[1]??null,score:by[0]?.[0]??-1,margin:(by[0]?.[0]??-1)-(by[1]?.[0]??-1)};}
function recognizeLevel(c){const im=pixelsROI(c,0,Math.floor(416*.72),Math.floor(286*.45),Math.floor(416*.995));if(!im)return [null,0];const w=im.width,h=im.height,m=new Uint8Array(w*h);for(let i=0,p=0;i<im.data.length;i+=4,p++){const [hh,s,v]=rgbHsv(im.data[i],im.data[i+1],im.data[i+2]);if(s<=125&&v>=178)m[p]=1;}const comps=binaryCC(m,w,h),glyphs=[];for(const z of comps){const gw=z.maxx-z.minx+1,gh=z.maxy-z.miny+1;if(gh>=45&&gh<=65&&gw>=15&&gw<=52&&z.miny>=48&&z.miny<=70&&z.minx+gw<=121&&z.area>=520){const sub=new Uint8Array(gw*gh);for(let yy=0;yy<gh;yy++)for(let xx=0;xx<gw;xx++)sub[yy*gw+xx]=m[(z.miny+yy)*w+z.minx+xx];glyphs.push([z.minx,normalizeGlyph(sub,gw,gh)]);}}glyphs.sort((a,b)=>a[0]-b[0]);if(!glyphs.length||glyphs.length>2)return [null,0];let text='',minScore=1,minMargin=1;for(const [,g] of glyphs){const r=classifyDigit(g,'level');if(!r.digit||r.score<.48){return [null,0];}text+=r.digit;minScore=Math.min(minScore,r.score);minMargin=Math.min(minMargin,r.margin);}const v=Number(text);if(!(v>=1&&v<=100))return [null,0];return [v,clamp(.82+.14*Math.min(1,(minScore-.48)/.35)+.04*Math.min(1,minMargin/.15),.82,.995)];}
function morphOpen2(mask,w,h){const e=new Uint8Array(mask.length),d=new Uint8Array(mask.length);for(let y=0;y<h-1;y++)for(let x=0;x<w-1;x++){let on=1;for(let yy=0;yy<2;yy++)for(let xx=0;xx<2;xx++)if(!mask[(y+yy)*w+x+xx])on=0;e[y*w+x]=on;}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let on=0;for(let yy=-1;yy<=0&&!on;yy++)for(let xx=-1;xx<=0;xx++){const X=x+xx,Y=y+yy;if(X>=0&&Y>=0&&X<w&&Y<h&&e[Y*w+X]){on=1;break;}}d[y*w+x]=on;}return d;}
function recognizeBloom(c){const im=pixelsROI(c,0,Math.floor(416*.42),Math.floor(286*.35),Math.floor(416*.71));if(!im)return [null,0];const w=im.width,h=im.height,m=new Uint8Array(w*h);for(let i=0,p=0;i<im.data.length;i+=4,p++){const [,s,v]=rgbHsv(im.data[i],im.data[i+1],im.data[i+2]);if(s<=80&&v>=200)m[p]=1;}const comps=binaryCC(m,w,h);let badge=null;for(const z of comps){const bw=z.maxx-z.minx+1,bh=z.maxy-z.miny+1;if(bw>=50&&bw<=72&&bh>=50&&bh<=72&&z.area>=1700&&z.area<=4200&&z.minx>=8&&z.maxx<=w-3&&z.miny>=12&&z.maxy<=h-3&&(!badge||z.area>badge.area))badge=z;}if(!badge)return [0,.98];const bx=badge.minx,by=badge.miny,bw=badge.maxx-bx+1,bh=badge.maxy-by+1,x0=Math.floor(.20*bw),x1=Math.max(x0+1,Math.floor(.84*bw)),y0=Math.floor(.13*bh),y1=Math.max(y0+1,Math.floor(.92*bh)),iw=x1-x0,ih=y1-y0,digit=new Uint8Array(iw*ih);for(let yy=0;yy<ih;yy++)for(let xx=0;xx<iw;xx++){const p=((by+y0+yy)*w+(bx+x0+xx))*4,r=im.data[p],g=im.data[p+1],b=im.data[p+2],gray=.299*r+.587*g+.114*b;if(gray<180)digit[yy*iw+xx]=1;}const opened=morphOpen2(digit,iw,ih),g=normalizeGlyph(opened,iw,ih),r=classifyDigit(g,'bloom');if(r.digit&&'12345'.includes(r.digit)&&r.score>=.40)return [Number(r.digit),clamp(.85+.14*Math.min(1,(r.score-.40)/.40),.85,.99)];return [null,.65];}
function fingerprint(c){const t=canvas(17,16),ctx=t.getContext('2d',{willReadFrequently:true});ctx.drawImage(c,35,185,215,65,0,0,17,16);const d=ctx.getImageData(0,0,17,16).data,bits=new Uint8Array(256);let k=0;for(let y=0;y<16;y++)for(let x=0;x<16;x++){const i=(y*17+x)*4,j=i+4,a=.299*d[i]+.587*d[i+1]+.114*d[i+2],b=.299*d[j]+.587*d[j+1]+.114*d[j+2];bits[k++]=b>a?1:0;}return bits;}
function hamming(a,b){let n=0;for(let i=0;i<256;i++)if(a[i]!==b[i])n++;return n;}
function detectSlots(bitmap,geom){
  // Preserve the fully validated desktop path. The adaptive branch is only needed
  // when the roster occupies a sub-panel and canonical card pitch is much smaller.
  if(!geom.mobileLayout){const slots=[],s=geom.pitch/BASE.pitch,ch=BASE.cardH*s,topOff=BASE.iconTop*s,kmin=Math.floor((-ch+topOff-geom.phase)/geom.rowPitch)-1,kmax=Math.ceil((geom.canonH+topOff-geom.phase)/geom.rowPitch)+1;for(let k=kmin;k<=kmax;k++){const y=geom.phase+k*geom.rowPitch,top=y-topOff,bottom=top+ch,vis=Math.max(0,Math.min(geom.canonH,bottom)-Math.max(0,top));if(vis<ch*.35)continue;for(let col=0;col<6;col++){let present=geom.iconScore(geom.xs[col],y)>.18;if(!present){const c=extractCard(bitmap,geom,y,col),[rar,rc]=classifyRarity(c.canvas);present=rar!=null&&rc>=.82;}if(present)slots.push({rowY:Math.round(y),col});}}return slots.sort((a,b)=>a.rowY-b.rowY||a.col-b.col);}
  const slots=[],s=geom.pitch/BASE.pitch,ch=BASE.cardH*s,topOff=BASE.iconTop*s,ys=geom.observedYs||[];let rowYs=[];
  if(ys.length){const ks=ys.map(y=>Math.round((y-geom.phase)/geom.rowPitch)),k0=Math.min(...ks),k1=Math.max(...ks);for(let k=k0;k<=k1;k++)rowYs.push(geom.phase+k*geom.rowPitch);const first=rowYs[0],firstTop=first-topOff,prev=first-geom.rowPitch,ptop=prev-topOff,pbottom=ptop+ch,pvis=Math.max(0,Math.min(geom.canonH,pbottom)-Math.max(0,ptop));if(firstTop<=ch*.35&&pvis>=ch*.40)rowYs.unshift(prev);const last=rowYs[rowYs.length-1],next=last+geom.rowPitch,ntop=next-topOff,nbottom=ntop+ch,nvis=Math.max(0,Math.min(geom.canonH,nbottom)-Math.max(0,ntop));if(nvis>=ch*.35)rowYs.push(next);}else rowYs=[geom.phase];
  for(const y of rowYs){const top=y-topOff,bottom=top+ch,vis=Math.max(0,Math.min(geom.canonH,bottom)-Math.max(0,top));if(vis<ch*.35)continue;for(let col=0;col<6;col++){let present=geom.iconScore(geom.xs[col],y)>.18;if(!present){const c=extractCard(bitmap,geom,y,col),[rar,rc]=classifyRarity(c.canvas);present=rar!=null&&rc>=.82;}if(present)slots.push({rowY:Math.round(y),col});}}
  return slots.sort((a,b)=>a.rowY-b.rowY||a.col-b.col);
}

async function init(msg){const load=(obj,url)=>obj??fetch(url).then(r=>r.json());const [cards,refs,digits]=await Promise.all([load(msg.cards,msg.cardsUrl),load(msg.refs,msg.refsUrl),load(msg.digits,msg.digitsUrl)]);REGISTRY=cards;BY_ID=new Map(cards.map(c=>[c.id,c]));REGISTRY_HASH=refs.registrySourceHash;REF_META=refs;for(const it of refs.items){const rgb=b64bytes(it.rgb);REFS.set(it.cardId,denseDescriptorFromRGB(rgb,refs.width,refs.height));}DIGITS={level:{},bloom:{}};for(const kind of ['level','bloom'])for(const [d,arr] of Object.entries(digits[kind]))DIGITS[kind][d]=arr.map(x=>{const b=b64bytes(x),f=new Float32Array(b.length);for(let i=0;i<b.length;i++)f[i]=b[i]/255;return f;});ready=true;return {registryCount:REGISTRY.length,referenceCount:REFS.size,indexFresh:REFS.size===REGISTRY.length};}
async function recognize(images){if(!ready)throw new Error('Recognizer is not initialized.');const instances=[],all=[];let instanceIndex=0;for(const item of images){const bitmap=item.bitmap,geom=fitGeometry(bitmap),slots=detectSlots(bitmap,geom);for(const s of slots){const ex=extractCard(bitmap,geom,s.rowY,s.col),[level,lc]=recognizeLevel(ex.canvas),[bloom,bc]=recognizeBloom(ex.canvas),[rarity,rc]=classifyRarity(ex.canvas),id=recognizeIdentity(ex.canvas,rc>=.8?rarity:null,ex.missingTop),fp=fingerprint(ex.canvas);instances.push({screenshot:item.name,rowAnchorY:s.rowY,column:s.col+1,cardBox:ex.box,visibleHeight:ex.visibleHeight,rarity,rarityConfidence:rc,level,levelConfidence:lc,bloom,bloomConfidence:bc,identity:id,fingerprint:Array.from(fp)});all.push({instanceIndex,level,lc,bloom,bc,rarity,rc,fp,id});instanceIndex++;}bitmap.close?.();}
  const groups=[],rep=[];for(let i=0;i<all.length;i++){const a=all[i];let bi=-1,bd=999;for(let g=0;g<rep.length;g++){const d=hamming(a.fp,rep[g]);if(d<bd){bd=d;bi=g;}}if(bi>=0&&bd<=50)groups[bi].push(i);else{groups.push([i]);rep.push(a.fp);}}
  const cards=[];for(const inds of groups){const mem=inds.map(i=>instances[i]),resolved=mem.filter(m=>m.identity.cardId),ids=[...new Set(resolved.map(m=>m.identity.cardId))],warnings=[];let ir,cid;if(ids.length===1){cid=ids[0];ir=resolved.filter(m=>m.identity.cardId===cid).sort((a,b)=>b.identity.confidence-a.identity.confidence)[0].identity;}else if(ids.length>1){cid=null;ir=resolved.sort((a,b)=>b.identity.confidence-a.identity.confidence)[0].identity;warnings.push('identity conflict across overlapping screenshots');}else{cid=null;ir=mem.sort((a,b)=>b.identity.confidence-a.identity.confidence)[0].identity;warnings.push('identity requires review');}const rec=cid?BY_ID.get(cid):null;let level=null,levelConf=0,bloom=null,bloomConf=0;for(const m of mem){if(m.level!=null&&m.levelConfidence>levelConf){level=m.level;levelConf=m.levelConfidence;}if(m.bloom!=null&&m.bloomConfidence>bloomConf){bloom=m.bloom;bloomConf=m.bloomConfidence;}}const uiR=[...new Set(mem.filter(m=>m.rarity!=null&&m.rarityConfidence>=.8).map(m=>m.rarity))];if(rec&&uiR.some(r=>r!==rec.rarity))warnings.push('rarity UI conflicts with matched card');if(level==null)warnings.push('level not visible; provide an overlapping screenshot or review manually');if(bloom==null)warnings.push('bloom stage requires review');cards.push({cardId:cid,member:rec?.member??null,name:rec?.name??null,rarity:rec?.rarity??(uiR.length===1?uiR[0]:null),level,bloom,identityConfidence:ir?.confidence??0,levelConfidence:levelConf,bloomConfidence:bloomConf,source:ir?.source??'unresolved',evidence:{instances:inds,candidateIds:ir?.candidateIds??[],alternatives:(ir?.alternatives??[]).slice(0,5)},warnings});}
  return {schemaVersion:1,apiVersion:API_VERSION,recognizerVersion:VERSION,registrySourceHash:REGISTRY_HASH,referenceIndexFresh:REFS.size===REGISTRY.length,registryCardCount:REGISTRY.length,referenceCardCount:REFS.size,warnings:REFS.size===REGISTRY.length?[]:[`reference index stale/incomplete: registry=${REGISTRY.length}, references=${REFS.size}`],cards,diagnostics:{perScreenshot:Object.fromEntries(images.map(x=>[x.name,instances.filter(i=>i.screenshot===x.name).length])),instances:instances.length,unique:cards.length,resolvedIdentity:cards.filter(c=>c.cardId).length,needsIdentityReview:cards.filter(c=>!c.cardId).length,needsProgressionReview:cards.filter(c=>c.level==null||c.bloom==null).length,instancesDetail:instances}};
}

self.onmessage=async e=>{const m=e.data;try{if(m.type==='init'){const s=await init(m);postMessage({type:'ready',...s});}else if(m.type==='recognize'){postMessage({type:'progress',phase:'recognizing',done:0,total:m.images.length});const result=await recognize(m.images);postMessage({type:'result',result});}}catch(err){postMessage({type:'error',message:err?.stack||err?.message||String(err)});}};
