const fs=require('fs');
const html=fs.readFileSync(process.argv[2],'utf8');
const master=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));
const cases=JSON.parse(fs.readFileSync(process.argv[4],'utf8'));
const start=html.indexOf('function materializeCard');
const end=html.indexOf('function chooseCount',start);
if(start<0||end<0) throw new Error('Could not locate materializeCard in HTML');
let code=html.slice(start,end);
code += `\n;globalThis.__materialized=${JSON.stringify(cases)}.map(q=>{const c=${JSON.stringify(master.cards)}.find(x=>x.id===q.id); return materializeCard(c,q.level,q.bloom);});`;
eval(code);
process.stdout.write(JSON.stringify(globalThis.__materialized));
