const fs=require('fs');
const html=fs.readFileSync(process.argv[2],'utf8');
const raw=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));
const version=process.argv[4];
const start=html.indexOf('const ATTR_LABEL={');
const end=html.indexOf('function materializeCard',start);
if(start<0||end<0) throw new Error('Could not locate browser normalization code in HTML');
let code=html.slice(start,end);
code += `\n;globalThis.__normalizationResult=normalizeHolodoriRaw(${JSON.stringify(raw)},${JSON.stringify(version)});`;
eval(code);
process.stdout.write(JSON.stringify(globalThis.__normalizationResult));
